[package]
name = "renderervk"
version = "0.1.0"
authors = ["rileylyman <rileylyman@berkeley.edu>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
image = "0.21"
winit = "0.18"
wavefront_obj = "6.0.0"
